default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres

development:
  <<: *default
  database: assemblyer_development
  # port: 5433

test:
  <<: *default
  database: assemblyer_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: assemblyer

 